web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - ./precision_machining_website:/app
  environment:
    - DEBUG=0
  links:
    - db

db:
  image: postgres:13
  environment:
    - POSTGRES_DB=machining_platform
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

# 移除nginx服务，因为版本1不支持一些高级特性
